#get menu method
get:
  #whether allow player to get menu by command(/mcmenu get <menu name>)
  #(OP is always allowed)
  cmd: true

#exit menu method
exit:
  #exit on movement
  move:
    enable: true
    #move distance,double value,>=0
    distance: 0.5
  #exit on open inventory
  openInventory:
    enable: false

#menu item display
lore:
  #menu item flag, color char & is allowed
  check: "&e+&aMenu&e+"
  #item title, color char & is allowed, {menu} represents menu name
  title: "&a{menu}"
  #description list, color char & is allowed
  descriptions:
    - "&eplace menu item in quickbar"
    - "&eenter menu/confirm: &7click menu item"
    - "&eback: &7click 8'th slot of quickbar"
    - "&eexit: &7move to exit"
    - "&emove left: &7click first slot of quickbar"
    - "&emove right: &7click 9'th slot of quickbar"
  #line of menu name, color char & is allowed, {menu} represents menu name
  menu: "&7({menu})"

#display
#avaiable display bars:
#  title: title in the center of screen
#  subTitle: sub title in the center of screen
#  tip: below subTitle
#  actionbar: below tip
#  popup: below actionbar
#  chat: chat window
display:
  #words limit, format is 'display-bar-name limit', default is no limit
  limit:
    - "title 16"
    - "subTitle 32"
    - "tip 64"
    - "actionbar 64"
    - "popup 64"
  #content refresh, format is 'display-bar-name interval(unit is tick)', default is no refresh
  #some display will fadeout, so refresh is needed
  refresh:
    - "tip 30"
    - "actionbar 30"
    - "popup 30"
  bar:
    #main display bar, is used to display menus
    main: "subTitle"
    #sub display bar, is used to display description
    sub: "actionbar"
  #display format
  format:
    #prefix of menus line, color char & is allowed
    start: ""
    #suffix of menus line, color char & is allowed
    end: ""
    #separator of menus line, color char & is allowed
    separator: " &c| "
    #format of current menu, {content} represents menu content, color char & is allowed
    current: "&a{content}"
    #format of not current menu, {content} represents menu content, color char & is allowed
    notCurrent: "&7{content}"
    #format of description, {content} represents menu description, color char & is allowed
    description: "&e{content}"

#sound(operate feedback,only called by operate using quickbar)
sound:
  #double value
  volume: 1.0
  #double value
  pitch: 1.0
  #sound on joining menu, optional
  join: "RANDOM_ORB"
  #sound on moving left, optional
  left: "RANDOM_POP"
  #sound on moving right, optional
  right: "RANDOM_POP"
  #sound on confirm, optional
  confirm: "RANDOM_POP"
  #sound on back, optional
  back: "RANDOM_POP"